public enum GameEventType
{
    PlayerTurnStart,
    PlayerTurnEnd,
    BallsTurnStart,
    BallsTurnEnd,
    MachineTurnStart,
    MachineTurnEnd,
    EnemyTouched,
    EnemyKilled,
    OnCollisionStart,
    OnCollisionEnd,
    OnScreenTouched,
    OnItemPicked, 
    OnItemDestroyed,
    OnItemEquiped,
    OnItemUSed,
    OnEnemySpawned,
    GameEnd
}
